[package]
name = "sprint"
version = "0.1.0"
edition = "2024"

[dependencies]
font-kit = { version = "0.14.3", features = ["freetype"] }
freedesktop-desktop-entry = "0.7.13"
meval = "0.2.0"
pathfinder_geometry = "0.5.1"
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31.10"
