# The font that Sprint will use throughout.
font = "FreeSans"

# The colors that Sprint should use.
background_color = [25, 25, 25]
foreground_color = [30, 30, 30]
seperator_color = [112, 69, 156]
selection_hover_color = [72, 43, 102]

# The template for generic web searches
# The variable %%QUERY%% is where the query is inserted into the URL, formatted as a GET parameter with spaces replaced with +
search_template = "https://duckduckgo.com/?q=%%QUERY%%"
# All web prefixes - The %%QUERY%% variable works as above.
web_prefixes = [
    # Knowledge
    ["Wikipedia", ">wiki", "https://en.wikipedia.org/w/index.php?search=%%QUERY%%"],
    ["StackExchange", ">exchange", "https://stackexchange.com/search?q=%%QUERY%%"],
    ["StackOverflow", ">overflow", "https://stackoverflow.com/search?q=%%QUERY%%"],

    # Social Media
    ["YouTube", ">yt", "https://www.youtube.com/results?search_query=%%QUERY%%"],
    ["GitHub", ">gh", "https://github.com/search?q=%%QUERY%%"],
    ["LinkedIn", ">lnkin", "https://www.linkedin.com/search/results/all/?keywords=%%QUERY%%"],
    ["Reddit", ">reddit", "https://www.reddit.com/search/?q=%%QUERY%%"],
    ["Facebook", ">facebook", "https://www.facebook.com/search/top/?q=%%QUERY%%"],

    # Search Engines
    ["Google", ">google", "https://www.google.com/search?q=%%QUERY%%"],
    ["Bing", ">bing", "https://www.bing.com/search?q=%%QUERY%%"],
    ["DuckDuckGo", ">ddg", "https://duckduckgo.com/?q=%%QUERY%%"],
]

# The order of the results, each entry should be one of the following; prefixes, math, desktop, search
result_order = ["prefixes", "math", "desktop", "search"]
